platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

# See: http://guides.cocoapods.org/making/making-a-cocoapod.html#release
# Once the pod has been released, use a version number here instead of a path.
target 'SampleBroadcaster' do
  #pod 'VideoCore', '~>0.1.12'
  pod 'VideoCore', path: '../..'
end

target 'SampleBroadcastUpload' do
  #pod 'FFmpeg', '~>2.8.3'
  pod 'VideoCore', path: '../..'
end
